// <auto-generated />
namespace FluentAPI_Start.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TPT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TPT));
        
        string IMigrationMetadata.Id
        {
            get { return "201404261517568_TPT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
