// <auto-generated />
namespace jQuery_CRUD.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update1));
        
        string IMigrationMetadata.Id
        {
            get { return "201405181521083_update1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
